### ISSUE TITLE
Contao 3.5

### ISSUE THREAD

**Issue by taleteller** [netzmacht/contao-leaflet-maps#36]
This Package is not installable via Composer using Contao 3.5, because the following requirement cannot be met:
contao/core >=3.2,<3.5-dev

Instead the core requirement should be:
contao/core >=3.2,<4.0-dev

**Comment by dmolineus** [comment]
Changed in ff8cda13716475fbb283e3c5c365f8f171bd25c2.

**Comment by taleteller** [comment]
Solved but not for its dependancies, see: netzmacht/contao-leaflet-libaries#1

**Comment by dmolineus** [comment]
I updated self maintained dependencies (netzmacht/contao-leaflet-libaries and contao-toolkit). Even though it's still not installable because some some 3rd party dependencies (https://github.com/contao-community-alliance/events-contao-bindings as dependency of the used https://github.com/contao-community-alliance/translator) does not support Contao 3.5 yet.

I leave this issue open as long as it's not fixed.

**Comment by dmolineus** [comment]
Ref: https://github.com/contao-community-alliance/events-contao-bindings/pull/8

**Comment by dmolineus** [comment]
Die Erweiterung lässt sich inzwischen unter Contao 3.5 installieren.
