### ISSUE TITLE
Database error on every backend page.

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-leaflet-maps#43]
Copied from https://github.com/netzmacht/contao-leaflet-maps/issues/42:

Also on the bottom of every backend page i get this:

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid connection resource' in /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Statement.php:92
Stack trace:
#0 /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Mysql.php(355): Contao\Database\Statement->__construct(Resource id #2, false)
#1 /var/customers/webs/moarhof/system/modules/core/library/Contao/Database.php(181): Contao\Database\Mysql->createStatement(Resource id #2, false)
#2 /var/customers/webs/moarhof/system/modules/core/classes/BackendUser.php(163): Contao\Database->prepare('UPDATE tl_user ...')
#3 [internal function]: Contao\BackendUser->__destruct()
#4 {main}
  thrown in /var/customers/webs/moarhof/system/modules/core/library/Contao/Database/Statement.php on line 92
```

**Comment by taleteller** [comment]
Testing some module conflicts it seems to happen when ``contao-bootstrap/bundle`` is installed. as soon as I disable either ``leaflet`` or ``bootstrap-core`` in the settings the error goes away. Contao Log does not provide anything beyond the Message above, neither does the contao debug mode.

**Comment by taleteller** [comment]
Addendum: Somewhere along the line the database instance seems to get destroyed before the backend session. When the described error appears, navigating with "Back" returns you to the wrong pages, visited long ago. Therefore the session never gets written back to the database. Since I cannot identify what kills the Session premature I hacked a 
```
 $this->Database = \Database::getInstance();
```
Into line 162 of ``modules\core\classes\BackendUser.php`` of Contao itself to restore functionality for now.

**Comment by dmolineus** [comment]
Actually the user class has to be loaded before the database. This is what contao-bootstrap does (https://github.com/contao-bootstrap/core/blob/master/src/Util/Contao.php#L24-L33) and Leaflet does as well by using the dependency-container only.

I can't reproduce it when using Bootstrap and Leaflet at the same time. So I guess the error is from another 3rd party extension. Unfortunately it's not possible to track the cause of the error in Contao.

**Comment by taleteller** [comment]
I found exactly the same behavior on a second Contao Installation I just updated from 3.4 to 3.5. This one on an different host. Disabling all third party plugins, the message appears as soon as bootstrap-core and leaflet come together:

```
04-May-2017 19:02:55 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid connection resource' in ROOT/system/modules/core/library/Contao/Database/Statement.php:92
Stack trace:
#0 ROOT/system/modules/core/library/Contao/Database/Mysql.php(355): Contao\Database\Statement->__construct(Resource id #186, false)
#1 ROOT/system/modules/core/library/Contao/Database.php(181): Contao\Database\Mysql->createStatement(Resource id #186, false)
#2 ROOT/system/modules/core/classes/BackendUser.php(163): Contao\Database->prepare('UPDATE tl_user ...')
#3 [internal function]: Contao\BackendUser->__destruct()
#4 {main} thrown in ROOT/system/modules/core/library/Contao/Database/Statement.php on line 92
```
Besides this does not happen during construction, but destruction process. Somehow BackendUser::__destruct gets called after the database instance already got closed. This is where my patch of BackendUser.php ended up with:
```
$db = \Database::getInstance();
$db->prepare("UPDATE " . $this->strTable . " SET session=? WHERE id=?")
  ->execute(serialize($session), $this->intId);
```
I dont mind the message, but keeping the session from being written is a real bummer. Might be the bug lies somewhere in the contao-bootstrap/core and leaflet is just the trigger.

**Comment by dmolineus** [comment]
I still cannot reproduce the issue. As the version 2.x is end of life as soon as Contao 3.5 is end of life, there won't be any fixes.
