### ISSUE TITLE
Missing /assets/js/leaflet-src.js.map

### ISSUE THREAD

**Issue by HumanDigital** [netzmacht/contao-leaflet-maps#79]
Failed to load resource: the server responded with a status of 404 ()
www.mysite.com/assets/js/leaflet-src.js.map
Contao: 4.7.5
Leaflet Maps for Contao: 3.1.4
Browser: Safari 12.1.1

**Comment by dmolineus** [comment]
The leaflet css sources contains a map source reference. As the resources are combined with the Contao combiner - the relative path changes and the map source reference locates to a file which does not exist. From my point of view this should be fixed in Contao.

It's not a real issue as the map sources are only a help for developers.
